### ISSUE TITLE
Enabling Folder scanning crash the program

### ISSUE THREAD

**Issue by guii** [pdherbemont/Glasses#76]
If you disable the folder scanning from preferences and then quit the program, reopen it and enabling it again it will crash the all program. It seems to be related with the line [_watchedFolderQuery startQuery]; in the method - (void)startWatchingFolders from the class VLCMediaLibrary but I'm unable to debug it.

**Comment by fkuehne** [comment]
It's a hang. Thanks for reporting!

Log:

#0  0x00007fff834d9eb6 in __semwait_signal ()
#1  0x00007fff834ddcd1 in _pthread_cond_wait ()
#2  0x00007fff864cf2c4 in _MDQueryMakeClientPortLocked ()
#3  0x00007fff864ce820 in _MDQueryExecute ()
#4  0x00007fff864cde0a in MDQueryExecute ()
#5  0x00007fff856702b6 in -[NSMetadataQuery _recreateQuery]()
#6  0x00007fff8566d202 in -[NSMetadataQuery startQuery]()
#7  0x000000010003a0bf in -[VLCLMediaLibrary startWatchingFolders](self=0x114bf35a0, _cmd=0x10004618b) at VLCMediaLibrary.m:552
#8  0x000000010003a1da in -[VLCLMediaLibrary scanFolderSettingDidChange](self=0x114bf35a0, _cmd=0x10004615e) at VLCMediaLibrary.m:567
#9  0x0000000100035f45 in -[VLCLMediaLibrary observeValueForKeyPath:ofObject:change:context:](self=0x114bf35a0, _cmd=0x7fff8523b6d0, keyPath=0x100054000, object=0x100415cb0, change=0x116401db0, context=0x10065bc90) at VLCMediaLibrary.m:145
#10 0x00007fff8559128e in NSKeyValueNotifyObserver ()
#11 0x00007fff85590d82 in NSKeyValueDidChange ()
#12 0x00007fff8557472f in -[NSObject(NSKeyValueObserverNotification) didChangeValueForKey:]()
#13 0x00007fff81c88bc9 in -[CFXPreferencesPropertyListSource setValue:forKey:]()
#14 0x00007fff81c88b3f in _CFXPreferencesSetValue ()
#15 0x00007fff855850d5 in -[NSUserDefaults(NSUserDefaults) setObject:forKey:]()
#16 0x00007fff84cf4cbf in -[NSUserDefaultsController _setSingleValue:forKey:]()
#17 0x00007fff855ebfbc in -[NSObject(NSKeyValueCoding) setValue:forKeyPath:]()
#18 0x00007fff84d0ec45 in -[NSBinder _setValue:forKeyPath:ofObject:mode:validateImmediately:raisesForNotApplicableKeys:error:]()
#19 0x00007fff84d0eafd in -[NSBinder setValue:forBinding:error:]()
#20 0x00007fff85100f16 in -[NSValueBinder _applyObjectValue:forBinding:canRecoverFromErrors:handleErrors:typeOfAlert:discardEditingCallback:otherCallback:callbackContextInfo:didRunAlert:]()
#21 0x00007fff85100d2c in -[NSValueBinder applyDisplayedValueHandleErrors:typeOfAlert:canRecoverFromErrors:discardEditingCallback:otherCallback:callbackContextInfo:didRunAlert:]()
#22 0x00007fff84d26556 in -[NSValueBinder performAction:]()
#23 0x00007fff84d263e3 in -[_NSBindingAdaptor _objectDidTriggerAction:bindingAdaptor:]()
#24 0x00007fff84c9a092 in -[NSControl sendAction:to:]()
#25 0x00007fff84d25a0b in -[NSCell trackMouse:inRect:ofView:untilMouseUp:]()
#26 0x00007fff84d56536 in -[NSButtonCell trackMouse:inRect:ofView:untilMouseUp:]()
#27 0x00007fff84d244b5 in -[NSControl mouseDown:]()
#28 0x00007fff84c3e763 in -[NSWindow sendEvent:]()
#29 0x00007fff84b73ee2 in -[NSApplication sendEvent:]()
#30 0x000000010001da9f in -[VLCApplication sendEvent:](self=0x100616ca0, _cmd=0x7fff85239b60, event=0x116401a00) at VLCApplication.m:285
#31 0x00007fff84b0a922 in -[NSApplication run]()
#32 0x00007fff84b035f8 in NSApplicationMain ()
#33 0x0000000100002377 in main (argc=1, argv=0x7fff5fbff7f0) at main.m:13
